apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-voting-app
spec:
  ingressClassName: nginx
  rules:
    - host: voting.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voting-service
                port:
                  number: 80
    - host: result.net
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: result-service
                  port:
                    number: 80
