---
apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    name: result-service
    app: voting-app
spec:
  selector:
    name: result-app-pod
    app: voting-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
